### ISSUE TITLE
Starting positions in Battle Mode do not save in current version

### ISSUE THREAD

**Issue by mmarino4** [thomasgoldstein/epicedit#10]
If you move the starting positions on a Battle Mode course, they will not save in the current version.  I tried in a previous version and they saved correctly.

**Comment by thomasgoldstein** [comment]
I just tried and it works for me. I moved a battle course starting position, saved the ROM, then reopened it. My change was still there. Track import / export also works. I'll need more information to reproduce the problem, like exact reproduction steps.

**Comment by mmarino4** [comment]
I tested it and it did it again but I see what is happening. When I move the starting positions, I don't see an asterisk at the top indicating that a change was made. So pressing Ctrl+S does nothing. As soon as I change anything else the asterisk pops up. Then I can save and it does retain the changes I made.

**Comment by thomasgoldstein** [comment]
It's fixed, thanks! 2.8.6 is out now.
