### ISSUE TITLE
Special Cup unlocked Permanently doesn't effect Time Trials (with solution)

### ISSUE THREAD

**Issue by mmarino4** [thomasgoldstein/epicedit#15]
When you make the changes to unlock Special Cup Permanently (in data pack 6), it does not have the tracks in time trials until you unlock them properly.  Here is the solution:

1C754->  Change 4F to C9
1C7C6 -> Change 28 to 38

The first change automatically displays the Special Cup in the list when you go to time trials. The second change allows you to move the arrow down there to select the track. The one issue is that it can take a second or two before you can actually get the arrow down there. Once it's unlocked properly, this doesn't happen.

**Comment by mmarino4** [comment]
> Hey. I tried it and get a crash when trying to access Time Trial, whether the rest of the hack (from pack 6) is applied or not.

Sorry, I was looking at the number next to it. It should be:
1C754-> Change 4F to 5D

**Comment by thomasgoldstein** [comment]
Cool, I'll take care of it later. Do you want to appear as mmarino4 in the credits?

**Comment by mmarino4** [comment]
> Cool, I'll take care of it later. Do you want to appear as mmarino4 in the credits?

DarthMarino would be preference since that's what I release my hack under.

**Comment by mmarino4** [comment]
The first change is just logical. It's telling the game to also use the location for the "4 cups available" format when special cup isn't unlocked. The second is just dumb luck that I found it by randomly changing that number and I don't really understand why it works. There might be a better method.

**Comment by thomasgoldstein** [comment]
The documentation has been updated, thank you for your contribution.
