### ISSUE TITLE
Track-Specific visual bugs

### ISSUE THREAD

**Issue by westslasher2** [thomasgoldstein/epicedit#8]
If you have an empty tile as the main tile in a track (tile 1) to be specific, and if the player drives off-course, lakitu will not show up unless it's in Ghost Valley or Rainbow Road to drop the player back on the course. Similarly when you try to shake off a monty mole in a track tileset other than donut plains then only part of his graphics will become visible instead of the whole thing.

**Comment by thomasgoldstein** [comment]
Thanks for the report, but this is the default game behavior and I don't know how to fix it. Ideally, everything about each track theme should be configurable, removing all the hardcoded bits, but that's way over my head. In the past, smkdan helped me with things like that. Closing, but I'm still open to help or contributions.
