### ISSUE TITLE
Can't properly edit background front layer in 2.8.4

### ISSUE THREAD

**Issue by mmarino4** [thomasgoldstein/epicedit#9]
When editing the front layer of the background in 2.8.4, you can't fully change sprites.  Only visible parts can be added. This was not the case in 2.8.3

**Comment by thomasgoldstein** [comment]
Hey @mmarino4, thanks for the bug report!
It took over 2 years for someone to report this. :)
Epic Edit 2.8.5 is out with this bug fixed. Enjoy.
